name: CoreRender
options:
  deploymentTarget:
    iOS: 10.0
  usesTabs: false
  indentWidth: 2
targets:
  CoreRender: &base
    platform: iOS
    type: framework
    sources:
      - path: src/
    headers:
      - src/CoreRender.h
      - src/deps/yoga/
      - src/
    settings:
      base:
        INFOPLIST_FILE: src/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: io.alexdrone.corerender
        PLATFORM: platform $platform
        GCC_GENERATE_DEBUGGING_SYMBOLS: YES
        GCC_DEBUGGING_SYMBOLS: full,
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        ONLY_ACTIVE_ARCH: NO
        SWIFT_OPTIMIZATION_LEVEL: -Owholemodule
        SWIFT_VERSION: 5
    postbuildScripts:
      - name: Dist
      - script: NAME="CoreRender";PRODUCT="${BUILT_PRODUCTS_DIR}";cp -R "${PRODUCT}/${NAME}.framework" ./bin;cp -R "${PRODUCT}/${NAME}.framework.dSYM" ./bin;cd ./bin;zip -r dist.zip *;
  Test:
    platform: iOS
    type: bundle.unit-test
    sources:
      - test
    dependencies:
      - target: CoreRender
    scheme:
      testTargets:
        - Test
      gatherCoverageData: true
      environmentVariables:
        - variable: TEST
          value: YES
          isEnabled: true
