name: CoreRender
options:
  deploymentTarget:
    iOS: 10.0
  usesTabs: false
  indentWidth: 2
targets:
  CoreRender: &base
    platform: iOS
    type: framework
    sources:
      - path: src/
    headers:
      - src/CoreRender.h
      - src/deps/yoga/
      - src/
    settings:
      base:
        INFOPLIST_FILE: src/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: io.alexdrone.CoreRender
        PLATFORM: platform $platform
        GCC_GENERATE_DEBUGGING_SYMBOLS: YES
        GCC_DEBUGGING_SYMBOLS: full,
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        ONLY_ACTIVE_ARCH: NO
        SWIFT_OPTIMIZATION_LEVEL: -Owholemodule
        # 3.0, 4.0 and 4,1 supported
        SWIFT_VERSION: 4.2
    postbuildScripts:
      - name: Dist
      - script: PRODUCT="${BUILT_PRODUCTS_DIR}/${TARGET_NAME}"; cp -R "${PRODUCT}.framework" ./bin; cp -R "${PRODUCT}.framework.dSYM" ./bin; cd ./bin; zip -r dist.zip "${PRODUCT}.framework.dSY" "${PRODUCT}.framework";
  Test:
    platform: iOS
    type: bundle.unit-test
    sources:
      - test
    dependencies:
      - target: CoreRender
    scheme:
      testTargets:
        - Test
      gatherCoverageData: true
      environmentVariables:
        - variable: TEST
          value: YES
          isEnabled: true
